<?php
// $Id$

/**
* Display help and module information
*/
function pclzip_help($path, $arg) {
  $output = '';
  switch ($path) {
    case "admin/help#pclzip":
      $output = '<p>'.  t('PclZip integration (see <a href="http://www.phpconcept.net/pclzip/index.en.php" target="_blank">the author\'s website</a> )') .'</p>';
      break;
  }
  return $output;
}

/*
* Build archive
*/
function pclzip_build_archive($filename) {
  // get the temp file
  global $pclzip_temp_file;
  $pclzip_temp_file = tempnam(sys_get_temp_dir(), $filename);

  // build the archive
  require_once('pclzip/pclzip.lib.php');
  return new PclZip($pclzip_temp_file);
}

/**
* Send the file
*/
function pclzip_send_file($filename) {
  global $pclzip_temp_file;
  // send the file
  header('Content-Type: application/zip') ;
  header('Content-Disposition: inline; filename='.$filename) ;
  header("Content-Transfer-Encoding: binary");
  header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
  header('Pragma: public');
  header("Expires: 0");
  header("Content-Length: ". filesize($pclzip_temp_file));
  readfile($pclzip_temp_file);
}